name: Test Release Pipeline

on:
  push:
    branches: [ "release" ]

env:
  PYTHON_VERSION: "3.8"
  POETRY_VERSION: "1.4.2"
  POETRY_URL: https://install.python-poetry.org

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        id: setup_python

      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          # install haskell implementation of pandoc as Python package is only wrapper
          # see https://stackoverflow.com/questions/62398231/building-docs-fails-due-to-missing-pandoc
          sudo apt install pandoc
          poetry config experimental.new-installer false
          poetry install --no-interaction --no-root --with docs
          pip install twine==4.0.2
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Install package
        run: |
          poetry install --no-interaction --only-root

      - name: Build docs
        run: |
          source `poetry env info --path`/bin/activate
          cd docs
          make clean html
          make html

      - name: Build package
        run: |
          poetry build

      - name: Check package
        run: |
          twine check --strict dist/*

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish:
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: test-release
      url: https://test.pypi.org/p/clusterxplain
    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
